version: '3.1'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      # be careful MYSQL_ROOT_PASSWORD: "" will parse
      # and set the password to two double quotes :grumpycat:
      - MYSQL_ROOT_PASSWORD=local
      # database contains invalid datetimes
    command: ["--sql-mode=no_engine_substitution"]
    volumes:
      - mysql_data:/var/lib/mysql
  mailcatcher:
    image: schickling/mailcatcher
    ports:
    - 1025:1025
    - 1080:1080
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  elasticsearch:
    image: elasticsearch:6.4.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
volumes:
  mysql_data:
